# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 476185c31c5fbceceea2041f5b2b727e66b83d4ca65fa36976f276142a0bf383e05eb192d4ed90c160735c6ab77e22b664bab84adf0c97c503e38dbc256b2f74

test:
  secret_key_base: 3aaf51d138d276d3779bf34decf77b2f381dcf36853067f7a0265eae00932835c1f42990baf1fc6d4bfb1a9e0e285a01cb28caff98c2b30b41dda67882c68a39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
